export type MediaKind = "anime" | "manga" | "manhwa" | "movie" | "tv";

export interface MediaItem {
  id: string;
  title: string;
  kind: MediaKind;
  genre: string;
  badge?: string; // "EP 24" | "CH 102" | "MOVIE"
  year?: number;
  rating?: number;
  synopsis: string;
  image: string;
  hero?: string;
  nsfw?: boolean; // adult/mature content flag (used by the explicit filter)
}

// Real cover art via AniList CDN (publicly cached)
const img = (id: number, size: "large" | "medium" = "large") =>
  `https://s4.anilist.co/file/anilistcdn/media/${id}/cover/${size}.jpg`;

export const SPOTLIGHT: MediaItem[] = [
  {
    id: "spot-1",
    title: "Solo Leveling",
    kind: "manhwa",
    genre: "Action • Fantasy",
    badge: "CH 200",
    year: 2024,
    rating: 9.1,
    synopsis:
      "In a world where hunters battle deadly monsters, the weakest E-rank Sung Jinwoo is given a second chance to level up without limit.",
    image:
      "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx142838-Kn5HwLkw83tn.jpg",
    hero: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/142838-1m1mfeKpZsLW.jpg",
  },
  {
    id: "spot-2",
    title: "Frieren: Beyond Journey's End",
    kind: "anime",
    genre: "Fantasy • Drama",
    badge: "S2 SOON",
    year: 2024,
    rating: 9.3,
    synopsis:
      "After defeating the Demon King, the elf mage Frieren begins a quiet journey to understand the humans she once travelled with.",
    image:
      "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx154587-mCQ5pcQX9w22.png",
    hero: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/154587-rdNiwhTUuVtl.jpg",
  },
  {
    id: "spot-3",
    title: "Dune: Part Two",
    kind: "movie",
    genre: "Sci-Fi • Epic",
    badge: "MOVIE",
    year: 2024,
    rating: 8.6,
    synopsis:
      "Paul Atreides unites with the Fremen to wage war against the Harkonnens and reclaim the desert planet of Arrakis.",
    image: "https://image.tmdb.org/t/p/w780/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg",
    hero: "https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
  },
];

export const CATALOG: MediaItem[] = [
  // Anime
  {
    id: "a1",
    title: "Frieren: Beyond Journey's End",
    kind: "anime",
    genre: "Fantasy",
    badge: "EP 28",
    year: 2024,
    rating: 9.3,
    synopsis: "An elf mage's quiet journey.",
    image: img(154587),
  },
  {
    id: "a2",
    title: "Jujutsu Kaisen",
    kind: "anime",
    genre: "Action",
    badge: "EP 47",
    year: 2023,
    rating: 8.7,
    synopsis: "Cursed energy and sorcerers.",
    image: img(145064),
  },
  {
    id: "a3",
    title: "Cyberpunk: Edgerunners",
    kind: "anime",
    genre: "Sci-Fi",
    badge: "S1",
    year: 2022,
    rating: 8.6,
    synopsis: "Street kid in Night City.",
    image: img(139274),
  },
  {
    id: "a4",
    title: "Chainsaw Man",
    kind: "anime",
    genre: "Horror",
    badge: "EP 12",
    year: 2022,
    rating: 8.5,
    synopsis: "Devil hunter Denji.",
    image: img(127230),
  },
  {
    id: "a5",
    title: "Demon Slayer",
    kind: "anime",
    genre: "Action",
    badge: "S4",
    year: 2024,
    rating: 8.7,
    synopsis: "Tanjiro's quest.",
    image: img(166240),
  },
  {
    id: "a6",
    title: "Spy x Family",
    kind: "anime",
    genre: "Comedy",
    badge: "EP 37",
    year: 2024,
    rating: 8.5,
    synopsis: "Fake family of spies.",
    image: img(140960),
  },
  {
    id: "a7",
    title: "Vinland Saga",
    kind: "anime",
    genre: "Historical",
    badge: "S2",
    year: 2023,
    rating: 8.8,
    synopsis: "Viking revenge & redemption.",
    image: img(136430),
  },
  {
    id: "a8",
    title: "Bocchi the Rock!",
    kind: "anime",
    genre: "Music",
    badge: "S1",
    year: 2022,
    rating: 8.4,
    synopsis: "Anxious guitarist forms a band.",
    image: img(130003),
  },

  // Manga
  {
    id: "m1",
    title: "One Piece",
    kind: "manga",
    genre: "Adventure",
    badge: "CH 1110",
    year: 1997,
    rating: 9.4,
    synopsis: "Pirates seeking the One Piece.",
    image: img(30013),
  },
  {
    id: "m2",
    title: "Berserk",
    kind: "manga",
    genre: "Dark Fantasy",
    badge: "VOL 42",
    year: 1989,
    rating: 9.5,
    synopsis: "Guts, the Black Swordsman.",
    image: img(30002),
  },
  {
    id: "m3",
    title: "Vagabond",
    kind: "manga",
    genre: "Historical",
    badge: "VOL 37",
    year: 1998,
    rating: 9.2,
    synopsis: "Miyamoto Musashi's path.",
    image: img(30007),
  },
  {
    id: "m4",
    title: "Vinland Saga",
    kind: "manga",
    genre: "Historical",
    badge: "CH 213",
    year: 2005,
    rating: 9.1,
    synopsis: "Thorfinn's epic.",
    image: img(30642),
  },
  {
    id: "m5",
    title: "Chainsaw Man",
    kind: "manga",
    genre: "Horror",
    badge: "CH 168",
    year: 2018,
    rating: 8.6,
    synopsis: "Devil hunter Denji.",
    image: img(105778),
  },
  {
    id: "m6",
    title: "Monster",
    kind: "manga",
    genre: "Thriller",
    badge: "VOL 18",
    year: 1994,
    rating: 9.0,
    synopsis: "Dr. Tenma hunts a monster.",
    image: img(30025),
  },
  {
    id: "m7",
    title: "Oyasumi Punpun",
    kind: "manga",
    genre: "Drama",
    badge: "VOL 13",
    year: 2007,
    rating: 9.0,
    synopsis: "Bittersweet coming of age.",
    image: img(64127),
  },
  {
    id: "m8",
    title: "Sun-Ken Rock",
    kind: "manga",
    genre: "Action",
    badge: "VOL 25",
    year: 2006,
    rating: 8.2,
    synopsis: "Japanese gangster in Korea.",
    image: img(46739),
  },

  // Manhwa
  {
    id: "mh1",
    title: "Solo Leveling",
    kind: "manhwa",
    genre: "Action",
    badge: "CH 200",
    year: 2018,
    rating: 9.1,
    synopsis: "The weakest hunter rises.",
    image: img(105398),
  },
  {
    id: "mh2",
    title: "Tower of God",
    kind: "manhwa",
    genre: "Adventure",
    badge: "CH 600",
    year: 2010,
    rating: 8.7,
    synopsis: "Climb the tower for everything.",
    image: img(85470),
  },
  {
    id: "mh3",
    title: "Omniscient Reader",
    kind: "manhwa",
    genre: "Fantasy",
    badge: "CH 200",
    year: 2020,
    rating: 9.0,
    synopsis: "A novel becomes reality.",
    image: img(125367),
  },
  {
    id: "mh4",
    title: "The Beginning After The End",
    kind: "manhwa",
    genre: "Fantasy",
    badge: "CH 195",
    year: 2018,
    rating: 8.4,
    synopsis: "King reborn in a magical world.",
    image: img(117345),
  },
  {
    id: "mh5",
    title: "Noblesse",
    kind: "manhwa",
    genre: "Supernatural",
    badge: "COMPLETE",
    year: 2007,
    rating: 8.3,
    synopsis: "Noble vampire awakens.",
    image: img(40542),
  },
  {
    id: "mh6",
    title: "Lookism",
    kind: "manhwa",
    genre: "Drama",
    badge: "CH 500",
    year: 2014,
    rating: 8.5,
    synopsis: "Two bodies, one mind.",
    image: img(110449),
  },
  {
    id: "mh7",
    title: "Eleceed",
    kind: "manhwa",
    genre: "Action",
    badge: "CH 300",
    year: 2018,
    rating: 9.0,
    synopsis: "Cat and the kid hero.",
    image: img(116691),
  },
  {
    id: "mh8",
    title: "Bastard",
    kind: "manhwa",
    genre: "Thriller",
    badge: "COMPLETE",
    year: 2014,
    rating: 8.6,
    synopsis: "Son of a serial killer.",
    image: img(85614),
  },

  // Movies
  {
    id: "mv1",
    title: "Dune: Part Two",
    kind: "movie",
    genre: "Sci-Fi",
    badge: "2024",
    year: 2024,
    rating: 8.6,
    synopsis: "Paul rises among the Fremen.",
    image: "https://image.tmdb.org/t/p/w500/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg",
  },
  {
    id: "mv2",
    title: "Oppenheimer",
    kind: "movie",
    genre: "Drama",
    badge: "2023",
    year: 2023,
    rating: 8.4,
    synopsis: "Father of the atomic bomb.",
    image: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
  },
  {
    id: "mv3",
    title: "Interstellar",
    kind: "movie",
    genre: "Sci-Fi",
    badge: "2014",
    year: 2014,
    rating: 8.7,
    synopsis: "Astronauts search for a new home.",
    image: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
  },
  {
    id: "mv4",
    title: "The Dark Knight",
    kind: "movie",
    genre: "Action",
    badge: "2008",
    year: 2008,
    rating: 9.0,
    synopsis: "Batman faces the Joker.",
    image: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911BytUrSxZSlh5.jpg",
  },
  {
    id: "mv5",
    title: "Inception",
    kind: "movie",
    genre: "Sci-Fi",
    badge: "2010",
    year: 2010,
    rating: 8.8,
    synopsis: "Dream thieves plant an idea.",
    image: "https://image.tmdb.org/t/p/w500/edv5CZvWj09upOsy2Y6IwDhK8bt.jpg",
  },
  {
    id: "mv6",
    title: "The Matrix",
    kind: "movie",
    genre: "Action",
    badge: "1999",
    year: 1999,
    rating: 8.7,
    synopsis: "A hacker discovers the truth.",
    image: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
  },
  {
    id: "mv7",
    title: "Gladiator",
    kind: "movie",
    genre: "Action",
    badge: "2000",
    year: 2000,
    rating: 8.5,
    synopsis: "A Roman general seeks vengeance.",
    image: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgCLYn.jpg",
  },
  {
    id: "mv8",
    title: "Parasite",
    kind: "movie",
    genre: "Thriller",
    badge: "2019",
    year: 2019,
    rating: 8.6,
    synopsis: "Two families converge.",
    image: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
  },
  {
    id: "mv9",
    title: "Interstellar",
    kind: "movie",
    genre: "Sci-Fi",
    badge: "2014",
    year: 2014,
    rating: 8.7,
    synopsis: "Astronauts search for a new home.",
    image: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
  },
  {
    id: "mv10",
    title: "Mad Max: Fury Road",
    kind: "movie",
    genre: "Action",
    badge: "2015",
    year: 2015,
    rating: 8.1,
    synopsis: "Post-apocalyptic wasteland chase.",
    image: "https://image.tmdb.org/t/p/w500/8tZYtuWezp8Jk7GYSzYynGnh5B.jpg",
  },

  // TV Shows
  {
    id: "tv-1",
    title: "Breaking Bad",
    kind: "tv",
    genre: "Crime • Drama",
    badge: "COMPLETE",
    year: 2008,
    rating: 9.2,
    synopsis: "A chemistry teacher turned meth kingpin.",
    image: "https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L3R5jNl8Z6Y0sW.jpg",
  },
  {
    id: "tv-2",
    title: "Game of Thrones",
    kind: "tv",
    genre: "Fantasy • Drama",
    badge: "COMPLETE",
    year: 2011,
    rating: 8.9,
    synopsis: "Families vie for the Iron Throne.",
    image: "https://image.tmdb.org/t/p/w500/u3bZgnGQ9T01sWNBveDZri3Uj7.jpg",
  },
  {
    id: "tv-3",
    title: "Stranger Things",
    kind: "tv",
    genre: "Sci-Fi • Horror",
    badge: "S5 SOON",
    year: 2016,
    rating: 8.6,
    synopsis: "Kids uncover supernatural secrets.",
    image: "https://image.tmdb.org/t/p/w500/49WJfeN0m4b4qWkY3qFCOl3QcF.jpg",
  },
  {
    id: "tv-4",
    title: "The Last of Us",
    kind: "tv",
    genre: "Drama • Horror",
    badge: "S2",
    year: 2023,
    rating: 8.8,
    synopsis: "Surviving a post-apocalyptic America.",
    image: "https://image.tmdb.org/t/p/w500/uKvGRjDmN9SJCzDZkOGLvJ5UV1.jpg",
  },
  {
    id: "tv-5",
    title: "The Boys",
    kind: "tv",
    genre: "Action • Comedy",
    badge: "S4",
    year: 2019,
    rating: 8.4,
    synopsis: "Ordinary people fight corrupt superheroes.",
    image: "https://image.tmdb.org/t/p/w500/2zmTngn1qO2j0W5WwYbM3I4nX.jpg",
  },
  {
    id: "tv-6",
    title: "Dark",
    kind: "tv",
    genre: "Sci-Fi • Mystery",
    badge: "COMPLETE",
    year: 2017,
    rating: 8.7,
    synopsis: "A family saga with a supernatural twist.",
    image: "https://image.tmdb.org/t/p/w500/apbrbWs8M9lyOpJYU5WXrpFbk1Z.jpg",
  },
  {
    id: "tv-7",
    title: "The Witcher",
    kind: "tv",
    genre: "Fantasy • Action",
    badge: "S3",
    year: 2019,
    rating: 8.1,
    synopsis: "A mutated monster hunter struggles to find his place.",
    image: "https://image.tmdb.org/t/p/w500/7vjaGThU3PZqR7ivRZdS2S3Ht.jpg",
  },
  {
    id: "tv-8",
    title: "Squid Game",
    kind: "tv",
    genre: "Thriller • Drama",
    badge: "S2",
    year: 2021,
    rating: 8.0,
    synopsis: "Desperate players risk their lives in a deadly game.",
    image: "https://image.tmdb.org/t/p/w500/dDlEmu3EZ0PggKZL3Uo9mUqkqY.jpg",
  },
  {
    id: "tv-9",
    title: "House of the Dragon",
    kind: "tv",
    genre: "Fantasy • Drama",
    badge: "S2",
    year: 2022,
    rating: 8.5,
    synopsis: "The history of House Targaryen.",
    image: "https://image.tmdb.org/t/p/w500/bQ6wThbdskE1d5V2Vq4u6JzXMj.jpg",
  },
  {
    id: "tv-10",
    title: "Better Call Saul",
    kind: "tv",
    genre: "Crime • Drama",
    badge: "COMPLETE",
    year: 2015,
    rating: 9.0,
    synopsis: "The transformation of Jimmy McGill into Saul Goodman.",
    image: "https://image.tmdb.org/t/p/w500/fC2H2j5j6o5y0qG8T1yMqGfM4a.jpg",
  },
  {
    id: "tv-11",
    title: "True Detective",
    kind: "tv",
    genre: "Crime • Mystery",
    badge: "S4",
    year: 2014,
    rating: 8.4,
    synopsis: "Anthology crime drama series.",
    image: "https://image.tmdb.org/t/p/w500/sq3D1s8vBXugyVK7qtP0yty6t3r.jpg",
  },
  {
    id: "tv-12",
    title: "The Office",
    kind: "tv",
    genre: "Comedy",
    badge: "COMPLETE",
    year: 2005,
    rating: 8.5,
    synopsis: "A mockumentary on a group of office workers.",
    image: "https://image.tmdb.org/t/p/w500/qwSU2imJ2bg5QNnCjSDB93zE3iS.jpg",
  },
];

export const ALL = [...SPOTLIGHT, ...CATALOG];

export const byKind = (k: MediaKind) => CATALOG.filter((m) => m.kind === k);
export const findById = (id: string) => ALL.find((m) => m.id === id);
